### ISSUE TITLE
cardano-metadata-submitter fails to finalize if policy has expired

### ISSUE THREAD

**Issue by AndrewWestberg** [input-output-hk/metadata-server#35]
I generated a policy intentionally intended to expire in order to have provably non-burnable tokens. When creating an entry in the metadata registry with cardano-metadata-submitter, it fails to finalize.

![Screenshot from 2021-03-03 04-33-54](https://user-images.githubusercontent.com/245918/109839249-d8ad8880-7c3e-11eb-85e1-2a03e426821a.png)

This seems like it is a valid use-case that should be covered as the tokens themselves are still very usable, but I would be unable to list them in the metadata registry without this issue being fixed.

**Comment by Liqwidfinance** [comment]
Are there any alternative options to include LQ in the metadata registry without going through the cardano-metadata-submitter process? Can we do this finalize step manually to get around the expired policy issue?

**Comment by KtorZ** [comment]
Hi, thanks for raising this. We've been scratching our heads around this quite a lot. So far the kept solution does indeed validate time constraints in the policy. It could be otherwise. That is, keys could attest for a policy modulo time constraints. 

The downside of the latter is that one would loose the ability to "transfer ownership" of the metadata over time (e.g. A policy which allows a set of keys before a date, and another set after).

Arguably, your use case sounds a bit more useful. 

We can easily lift that condition, it's technically feasible and it's a matter of decision at this stage. Incidentally, we've started to write a complete CIP for that to also leave the discussion open later, and have the community contribute to improvement.

I'll raise this internally.
